auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title
title: Fit Open 
timezone: UTC
collections:
  authors:
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
